name: Docker CI/CD - Dockerfile Nginx

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Docker
        run: docker --version

      - name: Build Docker Image
        run: |
          docker build -t nginx-image .

      - name: Run Container
        run: |
          docker run -d --name nginx-ci -p 8080:80 nginx-image

      - name: Verify Application
        run: |
          sleep 5
          curl http://localhost:8080

      - name: Destroy Environment (Always Runs)
        if: always()
        run: |
          docker stop nginx-ci || true
          docker rm nginx-ci || true
