name: Docker CI/CD - Ubuntu Nginx

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Verify Docker
      run: docker --version

    - name: Pull Ubuntu Image
      run: docker pull ubuntu:latest

    - name: Run Ubuntu Container
      run: |
        docker run -d --name nginx-ci ubuntu:latest sleep infinity

    - name: Install Nginx & Curl inside Container
      run: |
        docker exec nginx-ci apt update
        docker exec nginx-ci apt install -y nginx curl
        docker exec nginx-ci service nginx start

    - name: Verify Application
      run: |
        docker exec nginx-ci curl localhost

    - name: Destroy Environment (Always Runs)
      if: always()
      run: |
        docker stop nginx-ci || true
        docker rm nginx-ci || true
